const eventProfiles={koeo:{name:"Ignition on · engine off",rpm:"0",mafLb:"0.000",mafGs:"0.00 g/s",iat:"68",map:"14.5",stft:"0.0",ltft:"4.7",throttle:"17",voltage:"12.4",observation:"KOEO establishes whether MAF reports near-zero flow and whether IAT is plausible before the engine starts.",points:"0,190 80,189 160,190 240,188 320,189 400,190 480,189 560,190 640,189"},idle:{name:"Warm stabilized idle",rpm:"742",mafLb:"0.392",mafGs:"2.96 g/s",iat:"93",map:"4.3",stft:"6.3",ltft:"4.7",throttle:"14",voltage:"14.5",observation:"Warm idle asks whether airflow is non-zero, stable, and directionally consistent with MAP, load, and fuel correction.",points:"0,172 80,166 160,169 240,163 320,168 400,164 480,170 560,165 640,168"},rpm2500:{name:"Steady 2,500 RPM · no load",rpm:"2508",mafLb:"1.084",mafGs:"8.19 g/s",iat:"95",map:"6.8",stft:"3.1",ltft:"4.7",throttle:"22",voltage:"14.6",observation:"Steady elevated RPM tests whether reported airflow rises and stabilizes rather than remaining fixed or substituted.",points:"0,170 80,145 160,122 240,114 320,118 400,113 480,116 560,112 640,115"},snap:{name:"Controlled throttle transition",rpm:"3860",mafLb:"4.762",mafGs:"36.00 g/s",iat:"95",map:"12.9",stft:"0.8",ltft:"4.7",throttle:"71",voltage:"14.5",observation:"A controlled transition tests response shape and dropout behavior. Mock values illustrate interaction only; they are not pass/fail thresholds.",points:"0,170 70,168 140,160 210,125 280,52 350,28 420,68 490,115 560,148 640,166"}};
const evidence=new Set(["Fault context · P0102/P0113 relationship","MIL OFF · three confirmed codes"]);let currentStep="context";
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function addEvidence(text){evidence.add(text);renderEvidence()}
function renderEvidence(){const list=$("#evidence-list");if(!list)return;list.replaceChildren(...[...evidence].map(text=>{const li=document.createElement("li");li.textContent=text;return li}))}
function setStep(step){currentStep=step;$$('[data-step]').forEach(panel=>panel.hidden=panel.dataset.step!==step);let activeButton=null;$$('[data-step-target]').forEach(button=>{if(button.dataset.stepTarget===step){button.setAttribute("aria-current","step");activeButton=button}else button.removeAttribute("aria-current")});if(activeButton){const rail=activeButton.parentElement;rail.scrollTo({left:activeButton.offsetLeft-(rail.clientWidth-activeButton.offsetWidth)/2,behavior:"smooth"})}const panel=$(`[data-step="${step}"]`);panel?.scrollIntoView({behavior:"smooth",block:"start"})}
function setActiveEvent(key){const p=eventProfiles[key];if(!p)return;$$('[data-event]').forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.event===key)));$("#event-name").textContent=p.name;$("#pid-rpm").textContent=p.rpm;$("#pid-maf-imperial").textContent=p.mafLb;$("#pid-maf-metric").textContent=p.mafGs;$("#pid-iat").textContent=p.iat;$("#pid-map").textContent=p.map;$("#pid-stft").textContent=p.stft;$("#pid-ltft").textContent=p.ltft;$("#pid-throttle").textContent=p.throttle;$("#pid-voltage").textContent=p.voltage;$("#event-observation").textContent=p.observation;$("#trend-line").setAttribute("points",p.points);addEvidence(`Mock OBD event · ${p.name}`)}
$("#start-guide").addEventListener("click",()=>{$("#guided-workflow").hidden=false;addEvidence("Playbook revision · maf-circuit-low v0.1");setStep("context")});
$$('[data-step-target]').forEach(button=>button.addEventListener("click",()=>setStep(button.dataset.stepTarget)));$$('[data-step-next]').forEach(button=>button.addEventListener("click",()=>setStep(button.dataset.stepNext)));$$('[data-event]').forEach(button=>button.addEventListener("click",()=>setActiveEvent(button.dataset.event)));
$$('[data-history]').forEach(button=>button.addEventListener("click",()=>{$$('[data-history]').forEach(b=>b.classList.toggle("selected",b===button));const yes=button.dataset.history==="yes";$("#history-result").textContent=yes?"Context recorded: the codes may have been induced during prior testing; preserve timestamps before treating them as an active failure.":"Context recorded: no known intentional disconnect; continue with shared-circuit plausibility testing.";addEvidence(yes?"History · connector was intentionally disturbed":"History · no known intentional disconnect")}));
$$('[data-decision]').forEach(button=>button.addEventListener("click",()=>{$$('[data-decision]').forEach(b=>{if(b.parentElement===button.parentElement)b.classList.toggle("selected",b===button)});const inconclusive=button.dataset.decision.includes("inconclusive");$("#interpret-heading").textContent=inconclusive?"Electrical measurement needed":"OBD relationship appears plausible";$("#interpret-copy").textContent=inconclusive?"ECU-reported values cannot separate sensor output, circuit integrity, and ECU interpretation. Escalate to a synchronized scope capture.":"This answer lowers the value of immediate electrical escalation for that signal, but does not prove the component or circuit fault-free.";addEvidence(`Technician observation · ${button.textContent.trim()}`)}));
$("#escalate-scope").addEventListener("click",()=>{addEvidence("Decision · OBD evidence inconclusive; scope escalation selected");setStep("scope")});
$("#load-scope-preset").addEventListener("click",()=>{$("#scope-status").textContent="Preset loaded: A MAF signal · B sensor ground · C sensor supply. Wiring instructions remain blocked pending a verified vehicle overlay.";$("#scope-status").style.color="var(--live)";addEvidence("Pico preset · signal / ground / supply roles staged")});
$$('[data-fault]').forEach(button=>button.addEventListener("click",()=>{$$('[data-fault]').forEach(b=>{b.classList.toggle("selected",b===button);b.setAttribute("aria-pressed",String(b===button))})}));
$("#restart-guide").addEventListener("click",()=>{evidence.clear();evidence.add("Fault context · P0102/P0113 relationship");evidence.add("MIL OFF · three confirmed codes");renderEvidence();setActiveEvent("koeo");setStep("context")});renderEvidence();
